root.platform.defaultRoot = "/usr"
root.platform.localScratch = "./tests/condor_scratch"
root.platform.dataDirectory = "/tmp/data"
root.platform.fileSystemDomain = "lsstcorp.org"
root.platform.eupsPath = "/var/tmp"
