# flake8: noqa
config.platform.defaultRoot = "/usr"
config.platform.localScratch = "./tests/condor_scratch"
config.platform.dataDirectory = "/tmp/data"
config.platform.fileSystemDomain = "lsstcorp.org"
config.platform.eupsPath = "/var/tmp"
config.platform.scheduler = "pbs"
config.platform.setup_using = "setups"
config.platform.manager = "dagman"
