config.platform.defaultRoot = "/usr"
config.platform.localScratch = "./tests/condor_scratch"
config.platform.dataDirectory = "/tmp/data"
config.platform.fileSystemDomain = "lsstcorp.org"
config.platform.eupsPath = "/var/tmp"
